name: deathBanPlugin
description: $description
version: '${version}'

main: me.dev.micahcode.DeathBanPlugin
api-version: '26.2'
load: POSTWORLD

commands:
  autoban:
    description: Ban players when they die (need OP for this or deathBanPlugin.admin)
    usage: /autoban (on|off)
    permission: deathBanPlugin.admin
  bantime:
    description: The ban message of the ban
    usage: /banmessage <message>
    permission: deathBanPlugin.admin
  banmessage:
    description: The ban time of the ban
    usage: /banmessage <time>
    permission: deathBanPlugin.admin
  reload:
    description: Reload config.yml
    usage: /reload
    permission: deathBanPlugin.admin

permissions:
  deathBanPlugin.admin:
    description: Allows the user to run commands for the deathBanPlugin
    default: op

authors: [ MicahCode ]
website: https://micahcode.com/
